#!/usr/bin/env bash
# ---------------------------------------------------------------------------
#  Same build as build.ps1, for running directly on the Linux server
#  (e.g. from a git post-receive hook or a cron pull). Needs: jq
#
#      ./build.sh                       # uses baseUrl from toolbox.config.json
#      ./build.sh https://tools.me.dev  # override
# ---------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")"

command -v jq >/dev/null || { echo "jq is required: apt install jq"; exit 1; }

if [ ! -f toolbox.config.json ]; then
  echo "No toolbox.config.json yet. Create it from the example:"
  echo "  cp toolbox.config.example.json toolbox.config.json"
  echo "then set baseUrl to your own domain."
  exit 1
fi

BASE_URL="${1:-$(jq -r '.baseUrl' toolbox.config.json)}"
VERSION="$(jq -r '.version' toolbox.config.json)"
BASE_URL="${BASE_URL%/}"

rm -rf dist && mkdir -p dist

# --- catalog -> manifest.json ----------------------------------------------
collect() {
  local dir="catalog/$1"
  if compgen -G "$dir/*.json" >/dev/null; then
    jq -s 'add' "$dir"/*.json
  else
    echo '[]'
  fi
}

APPS=$(collect apps)
TWEAKS=$(collect tweaks)
SCRIPTS=$(collect scripts)
PRESETS=$([ -f catalog/presets.json ] && cat catalog/presets.json || echo '[]')

jq -n \
  --argjson apps    "$APPS" \
  --argjson tweaks  "$TWEAKS" \
  --argjson scripts "$SCRIPTS" \
  --argjson presets "$PRESETS" \
  --arg     version "$VERSION" \
  --arg     generated "$(date -Iseconds)" \
  '{generated:$generated, version:$version, apps:$apps, tweaks:$tweaks, scripts:$scripts, presets:$presets}' \
  > dist/manifest.json

# fail loudly on duplicate ids rather than shipping an ambiguous catalog
for kind in apps tweaks scripts; do
  dupes=$(jq -r ".$kind | group_by(.id) | map(select(length>1) | .[0].id) | .[]" dist/manifest.json)
  if [ -n "$dupes" ]; then echo "duplicate $kind id(s): $dupes"; exit 1; fi
done

# --- src -> toolbox.ps1 ------------------------------------------------------
{
  echo "# Toolbox $VERSION - built $(date '+%Y-%m-%d %H:%M')"
  echo "# Generated by build.sh - edit src/*.ps1 instead."
  for f in src/*.ps1; do
    printf '\n#region %s\n' "$(basename "$f")"
    cat "$f"
    printf '#endregion\n'
  done
} | sed -e "s|{{BASE_URL}}|$BASE_URL|g" \
        -e "s|{{VERSION}}|$VERSION|g" \
        -e "s|{{BUILD_DATE}}|$(date '+%Y-%m-%d')|g" \
  > dist/toolbox.ps1

cp -r payloads dist/payloads

# --- preset shortcuts ---------------------------------------------------------
# Caddy tries `{path}/toolbox.ps1` before falling back to `{path}` (see
# server/Caddyfile), so dist/<preset-id>/toolbox.ps1 makes
# `irm $BASE_URL/<preset-id> | iex` install that preset headless, no env var
# or GUI needed.
for id in $(echo "$PRESETS" | jq -r '.[].id'); do
  mkdir -p "dist/$id"
  { printf '$env:TOOLBOX_PRESET = %s\n' "$(jq -n --arg id "$id" '$id')"; cat dist/toolbox.ps1; } > "dist/$id/toolbox.ps1"
done

echo "Built dist/toolbox.ps1 ($(du -h dist/toolbox.ps1 | cut -f1)) for $BASE_URL"
echo "  $(jq '.apps|length' dist/manifest.json) apps, $(jq '.tweaks|length' dist/manifest.json) tweaks, $(jq '.scripts|length' dist/manifest.json) scripts"
echo "One-liner:  irm $BASE_URL | iex"
if [ "$(echo "$PRESETS" | jq 'length')" -gt 0 ]; then
  echo "Preset shortcuts:"
  echo "$PRESETS" | jq -r '.[] | "  irm '"$BASE_URL"'/\(.id) | iex   (\(.name))"'
fi
