<#
    Builds dist\ from src\ + catalog\ + payloads\.

        .\build.ps1                     # normal build
        .\build.ps1 -Serve              # build, then serve dist\ on :8080 for testing
        .\build.ps1 -BaseUrl http://localhost:8080

    dist\toolbox.ps1   - the single file your one-liner downloads
    dist\manifest.json - every catalog\**\*.json merged together
    dist\payloads\     - the .ps1 files individual entries pull in
#>
[CmdletBinding()]
param(
    [string] $BaseUrl,
    [switch] $Serve,
    [int]    $Port = 8080
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$configPath = Join-Path $root 'toolbox.config.json'
if (-not (Test-Path $configPath)) {
    Write-Host 'No toolbox.config.json yet. Create it from the example:' -ForegroundColor Yellow
    Write-Host '  copy toolbox.config.example.json toolbox.config.json' -ForegroundColor Cyan
    Write-Host 'then set baseUrl to your own domain.' -ForegroundColor Yellow
    exit 1
}
$config = Get-Content $configPath -Raw | ConvertFrom-Json
if (-not $BaseUrl) { $BaseUrl = $config.baseUrl }
$dist = Join-Path $root 'dist'

Remove-Item $dist -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $dist -Force | Out-Null

function Write-Utf8NoBom {
    # PS 5.1's -Encoding UTF8 writes a byte-order mark. Invoke-RestMethod hands
    # that BOM straight to iex, which dies on "Unexpected token", and
    # ConvertFrom-Json rejects it as an invalid JSON primitive. Neither shows up
    # when the same files are read off disk, because Get-Content strips it.
    param([string] $Path, [string] $Text)
    [IO.File]::WriteAllText($Path, $Text, (New-Object Text.UTF8Encoding($false)))
}

# --- 1. catalog -> manifest.json --------------------------------------------

function Read-CatalogDir {
    param([string] $Name)
    $dir = Join-Path $root "catalog\$Name"
    if (-not (Test-Path $dir)) { return @() }
    $items = @()
    foreach ($file in Get-ChildItem $dir -Filter *.json | Sort-Object Name) {
        try {
            # PS 5.1 hands a JSON array to the pipeline as ONE object, so @() would
            # wrap it instead of unrolling it.
            $data   = Get-Content $file.FullName -Raw | ConvertFrom-Json
            $parsed = if ($data -is [Array]) { $data } else { @($data) }
        } catch {
            throw "$($file.Name): invalid JSON - $($_.Exception.Message)"
        }
        foreach ($item in $parsed) {
            if (-not $item.id)   { throw "$($file.Name): an entry is missing 'id'" }
            if (-not $item.name) { throw "$($file.Name): '$($item.id)' is missing 'name'" }
            $items += $item
        }
        Write-Host ("  {0,-24} {1,3} entries" -f $file.Name, @($parsed).Count) -ForegroundColor DarkGray
    }
    $items
}

Write-Host 'Catalog:' -ForegroundColor Cyan
$apps    = Read-CatalogDir 'apps'
$tweaks  = Read-CatalogDir 'tweaks'
$scripts = Read-CatalogDir 'scripts'
$presets = @()
$presetFile = Join-Path $root 'catalog\presets.json'
if (Test-Path $presetFile) {
    $data    = Get-Content $presetFile -Raw | ConvertFrom-Json
    $presets = if ($data -is [Array]) { $data } else { @($data) }
}

# duplicate ids would make presets ambiguous
foreach ($set in @(@{ N = 'apps'; V = $apps }, @{ N = 'tweaks'; V = $tweaks }, @{ N = 'scripts'; V = $scripts })) {
    $dupes = $set.V | Group-Object id | Where-Object Count -gt 1
    if ($dupes) { throw "duplicate $($set.N) id(s): $($dupes.Name -join ', ')" }
}

# presets referencing entries that no longer exist are a warning, not an error
$known = @{ apps = $apps.id; tweaks = $tweaks.id; scripts = $scripts.id }
foreach ($preset in $presets) {
    foreach ($kind in 'apps', 'tweaks', 'scripts') {
        foreach ($id in @($preset.$kind)) {
            if ($id -and $known[$kind] -notcontains $id) {
                Write-Host "  ! preset '$($preset.name)' references unknown $kind id '$id'" -ForegroundColor Yellow
            }
        }
    }
}

$manifestJson = [ordered]@{
    generated = (Get-Date -Format 'o')
    version   = $config.version
    apps      = $apps
    tweaks    = $tweaks
    scripts   = $scripts
    presets   = $presets
} | ConvertTo-Json -Depth 12
Write-Utf8NoBom -Path (Join-Path $dist 'manifest.json') -Text $manifestJson

# --- 2. src -> toolbox.ps1 ---------------------------------------------------

Write-Host 'Source:' -ForegroundColor Cyan
$parts = Get-ChildItem (Join-Path $root 'src') -Filter *.ps1 | Sort-Object Name
$sb    = New-Object Text.StringBuilder
[void]$sb.AppendLine("# Toolbox $($config.version) - built $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
[void]$sb.AppendLine("# Generated by build.ps1 - edit src\*.ps1 instead.")
foreach ($part in $parts) {
    [void]$sb.AppendLine("`n#region $($part.Name)")
    [void]$sb.AppendLine((Get-Content $part.FullName -Raw))
    [void]$sb.AppendLine("#endregion")
    Write-Host ("  {0,-24} {1,4} lines" -f $part.Name, (Get-Content $part.FullName).Count) -ForegroundColor DarkGray
}

$code = $sb.ToString().
    Replace('{{BASE_URL}}',   $BaseUrl.TrimEnd('/')).
    Replace('{{VERSION}}',    $config.version).
    Replace('{{BUILD_DATE}}', (Get-Date -Format 'yyyy-MM-dd'))

$errors = $null
[void][System.Management.Automation.Language.Parser]::ParseInput($code, [ref]$null, [ref]$errors)
if ($errors) {
    $errors | ForEach-Object { Write-Host "  $($_)" -ForegroundColor Red }
    throw 'the bundled script does not parse - fix the errors above'
}

Write-Utf8NoBom -Path (Join-Path $dist 'toolbox.ps1') -Text $code

# --- 3. payloads -------------------------------------------------------------

Copy-Item (Join-Path $root 'payloads') (Join-Path $dist 'payloads') -Recurse -Force

# --- 4. preset shortcuts ------------------------------------------------------
# Caddy tries `{path}/toolbox.ps1` before falling back to `{path}` (see
# server/Caddyfile), so dist\<preset-id>\toolbox.ps1 makes
# `irm $BaseUrl/<preset-id> | iex` install that preset headless, no env var
# or GUI needed.

foreach ($preset in $presets) {
    $presetId  = ('' + $preset.id).Replace("'", "''")
    $presetDir = Join-Path $dist $preset.id
    New-Item -ItemType Directory -Path $presetDir -Force | Out-Null
    $presetCode = "`$env:TOOLBOX_PRESET = '$presetId'`n" + $code
    Write-Utf8NoBom -Path (Join-Path $presetDir 'toolbox.ps1') -Text $presetCode
}

$size = [Math]::Round((Get-Item (Join-Path $dist 'toolbox.ps1')).Length / 1KB, 1)
Write-Host ''
Write-Host "Built dist\toolbox.ps1 ($size KB) for $BaseUrl" -ForegroundColor Green
Write-Host "  $(@($apps).Count) apps  $(@($tweaks).Count) tweaks  $(@($scripts).Count) scripts  $(@($presets).Count) presets" -ForegroundColor DarkGray
Write-Host ''
Write-Host "One-liner:  irm $BaseUrl | iex" -ForegroundColor Cyan
if ($presets) {
    Write-Host 'Preset shortcuts:' -ForegroundColor Cyan
    foreach ($preset in $presets) {
        Write-Host "  irm $BaseUrl/$($preset.id) | iex   ($($preset.name))" -ForegroundColor DarkGray
    }
}

if ($Serve) { & (Join-Path $root 'tools\serve.ps1') -Port $Port }
